### ISSUE TITLE
Packges installed by brew in packages.yaml

### ISSUE THREAD

**Issue by pramodskumbhar** [pramodskumbhar/spack-packages#16]
Brew says:

```
For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig
```

Currently our `packages.yaml` has:

```
    openssl:
        paths:
            openssl@system: /usr/local
        buildable: False
        version: [system]
```

Do we need to put proper path i.e. ` /usr/local/opt/openssl` ?
